version: "3.9"
services:
  angular:
    build:
      context: .build/angular/
      dockerfile: dockerfile
    image: "${PROJECT_NAME}-angular"
    volumes:
      - .build/angular:/code/
    command: /bin/sh entrypoint.sh
    env_file:
      - .build/angular/environment.conf

  django:
    image: "${PROJECT_NAME}-django"
    build:
      context: .build/django/
      dockerfile: dockerfile
    volumes:
     - .build/django:/code/
    depends_on:
      postgres:
        condition: service_healthy
    command: /bin/sh entrypoint.sh
    environment:
      - "DJANGO_SETTINGS_MODULE=${PROJECT_NAME}.settings"
      # List apps in one comment i.e 'APPS="test", "test1", "test2"' #IMPORTANT a space between ,
      - PROJECT_NAME=default
      - THIRD_PARTY_APPS=['api', "main"]
      - ALLOWED_HOSTS=["*"]

    env_file:
      - .build/django/environment.conf

  postgres:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .build/postgres/data:/var/lib/postgresql/data/pgdata:rw
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
