FROM python:3 as default
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code/
RUN apt-get update -y && \
    apt-get upgrade -y
RUN apt-get install nodejs npm -y
COPY . /code/
RUN pip3 install -q -r requirements.txt
